### ISSUE TITLE
Different file format spotted in the wild! Can't extract TMOD 0.10.1.5, only 0.11.7.5 — All files are full of NULL, +unhandled exception at tModUnpacker.RawImage.RawToPng:42

### ISSUE THREAD

**Issue by 3ICE** [IVogel/tModUnpacker#5]
Continuing from my adventures in https://github.com/IVogel/tModUnpacker/issues/2#issuecomment-667618846...

I got the tool to run, and it works very well on most files I tested it with. Except for:
[UpgradeBackup.zip](https://github.com/IVogel/tModUnpacker/files/5011610/UpgradeBackup.zip)

And another example (smaller):
[QualityLogoMod.zip](https://github.com/IVogel/tModUnpacker/files/5011600/QualityLogoMod.zip)

The zip files contain the extraction result as well; Yes, they are all empty files. Correct size, but no contents.

Expected result:
```
>tModUnpacker.exe QualityLogoMod.tmod
QualityLogoMod
        Writing: Info
        Writing: Windows.dll
        Writing: Mono.dll
        Writing: description.txt
        Writing: QualityLogoMod.csproj.user
        Writing: Logo.rawimg
        Writing: Logo2.rawimg
```
The mod name is visible on line one.

Instead, this error pops up:
```
>tModUnpacker.exe UpgradeBackup\QualityLogoMod.tmod
        Writing: Info
        Writing: Windows.dll
        Writing: Mono.dll
        Writing: description.txt
        Writing: QualityLogoMod.csproj.user
        Writing: Logo.rawimg

Unhandled Exception: System.ArgumentException: Parameter is not valid.
   at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   at tModUnpacker.RawImage.RawToPng(Byte[] image)
   at tModUnpacker.tMod.DumpFile(String outputpath, String filename)
   at tModUnpacker.tMod.DumpFiles(String outputpath, Action`1 func)
   at tModUnpacker.main.Main(String[] args)

C:\Users\3ICE\OneDrive\Documents\My Games\Terraria\ModLoader\Mods>

```

The mod name is not visible on the first line this time. It gets to writing right away. Writing only NULLs, that is.

Debug build has line numbers but to get it to compile I broke the $ stringbuilder of course:
```
tModUnpacker\bin\Debug>tModUnpacker.exe "UpgradeBackup\QualityLogoMod.tmod"
        Writing: {filename}
        Writing: {filename}
        Writing: {filename}
        Writing: {filename}
        Writing: {filename}
        Writing: {filename}

Unhandled Exception: System.ArgumentException: Parameter is not valid.
   at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   at tModUnpacker.RawImage.RawToPng(Byte[] image) in tModUnpacker\RawImage.cs:line 42
   at tModUnpacker.tMod.DumpFile(String outputpath, String filename) in tModUnpacker\tMod.cs:line 186
   at tModUnpacker.tMod.DumpFiles(String outputpath, Action`1 func) in tModUnpacker\tMod.cs:line 209
   at tModUnpacker.main.Main(String[] args) in tModUnpacker\main.cs:line 33

tModUnpacker\bin\Debug>
```

Additionally, every single file is filled with nullbytes only.

File headers (not working vs current):
TMOD0.10.1.5:ù...
TMOD0.11.7.5å®K...

--3ICE

**Comment by 3ICE** [comment]
Windows Reliability Monitor has this to say on the problem...

My compiled version:
```
Description
Faulting application name: tModUnpacker.exe, version: 1.1.1.1, time stamp: 0x5f262437
Faulting module name: KERNELBASE.dll, version: 10.0.18362.959, time stamp: 0x51671cfe
Exception code: 0xe0434352
Fault offset: 0x001143d2
Faulting process id: 0x342c
Faulting application start time: 0x01d668749fa60d0a
Faulting application path: C:\Users\3ICE\Downloads\tModUnpacker-master\tModUnpacker\bin\Debug\tModUnpacker.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 0ff96575-132a-4b1f-a1d8-afdf82ade612
Faulting package full name: 
Faulting package-relative application ID: 
```

Release version:
```
Description
Faulting application name: tModUnpacker.exe, version: 1.0.0.0, time stamp: 0xfba03c35
Faulting module name: KERNELBASE.dll, version: 10.0.18362.959, time stamp: 0x51671cfe
Exception code: 0xe0434352
Fault offset: 0x001143d2
Faulting process id: 0x2460
Faulting application start time: 0x01d6687b78623030
Faulting application path: C:\Users\3ICE\OneDrive\Documents\My Games\Terraria\ModLoader\Mods\tModUnpacker.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 5a15bc80-5bda-471b-be16-8983e00df129
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by IVogel** [comment]
It should be working now.
It was a very stupid bug.
Also, added release links to the README.md

**Comment by 3ICE** [comment]
Tested, works very well, thank you.

For future releases you can skip these two files:
tModUnpacker.pdb (debugging database, not needed to run, only debug (i.e.: symbols))
tModUnpacker.exe.config (I just extracted the exe and it seems to work without config)
